apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotcop
  namespace: lab
  labels:
    service: load
spec:
  replicas: 1
  selector:
    matchLabels:
      service: robotcop
  template:
    metadata:
      labels:
        service: robotcop
    spec:
      containers:
      - name: robotcop
        env:
          - name: HOST
            value: "http://web:8080/"
          - name: NUM_CLIENTS
            value: "15"
          - name: SILENT
            value: "1"
          - name: ERROR
            value: "1"
        image: robotshop/rs-load:latest
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: robotcop
  namespace: lab
spec:
  selector:
    app: robotcop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082   
  type: NodePort