apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: ghcr.io/librespeed/speedtest:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: dev
spec:
  selector:
    app: speedtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085   
  type: NodePort
