apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-vaf
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest-vaf
  template:
    metadata:
      labels:
        app: speedtest-vaf
    spec:
      containers:
      - name: speedtest-vaf
        image: openspeedtest/latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-vaf
  namespace: production
spec:
  selector:
    app: speedtest-vaf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30086   
  type: NodePort
