apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftp-svr
  name: ftp-svr
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-svr
  strategy: {}
  template:
    metadata:
      labels:
        app: ftp-svr
    spec:
      containers:
      - image: delfer/alpine-ftp-server:latest
        name: ftp-server
        resources: {}
        env:
        - name: USERS
          value: "valbury|P@ssw0rd1!"
        ports:
        - name: port1
          containerPort: 21
        - name: port2
          containerPort: 21000


---
apiVersion: v1
kind: Service
metadata:
  name: ftp-server
  namespace: production
spec:
  selector:
    app: ftp-server
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      nodePort: 30089 
  type: NodePort


