apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: pesbuk-db
        image: mwbowo/pesbuk-db:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: db
          containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 75
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 75
          periodSeconds: 10
        
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: production
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: db
      nodePort: 30084   
  type: NodePort
