apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-fe
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pesbuk
  template:
    metadata:
      labels:
        app: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: mwbowo/pesbuk:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk-fe
  namespace: dev
spec:
  selector:
    app: pesbuk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083   
  type: NodePort
