apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pesbuk
  template:
    metadata:
      labels:
        app: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: mwbowo/pesbuk-db:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk
  namespace: dev
spec:
  selector:
    app: pesbuk
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30084   
  type: NodePort
