apiVersion: apps/v1
kind: Deployment
metadata:
  name: peppermint-fe
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peppermint
  template:
    metadata:
      labels:
        app: peppermint
    spec:
      containers:
      - name: peppermint
        image: pepperlabs/peppermint:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "128m"
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: peppermint-fe
  namespace: production
spec:
  selector:
    app: peppermint
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30090
  type: NodePort